# Introduction to Computer Vision S24 Assignment #1 
2019-12172 이재원, SNU

## Camera Calibration
- A 3 × 4 camera projection matric $\mathbf{P}$ maps a world point $𝐗_i = [𝑋_i 𝑌_i 𝑍_i 1]$
 to its 
corresponding image point $𝐱_i = 𝜔[𝑢_i 𝑣_i 1]$
 such that $𝐱_i = 𝐏𝐗_i$
, which gives two 
equations w.r.t. the unknown parameters of 𝐏 = [𝑚_ij]:

- Given 𝑛 ≥ 6 pairs of corresponding points, we have an over-determined system of equations, 
𝐀𝐩 = 𝟎, where p is the vectorized form of P. 
- Consider the SVD of A as $𝐀 = 𝐔𝐃𝐕^T$
. Then the least square solution 𝐩 = 𝑎𝑟𝑔𝑚𝑖𝑛𝐩‖𝐀𝐩‖,
‖𝐩‖=1 is the last column of 𝐕, which is the singular vector corresponding to the smallest 
singular value. Then, you can construct the camera projection matrix P using p up to scale. 

## Proof
### a) Show that the solution p is the last column of 𝐕 correspoding to the smallest singular value of A

in report

In [1]:
import numpy as np

In [2]:
u_v = [
[880, 214],
[43, 203],
[270, 197],
[886, 347],
[745, 302],
[943, 128],
[476, 590],
[419, 214],
[317, 335],
[783, 521],
[235, 427],
[665, 429],
[655, 362],
[427, 333],
[412, 415],
[746, 351],
[434, 415],
[525, 234],
[716, 308],
[602, 187]
]

In [3]:
xyz = [
[312.747, 309.140, 30.086],
[305.796, 311.649, 30.356],
[307.694, 312.358, 30.418],
[310.149, 307.186, 29.298],
[311.937, 310.105, 29.216],
[311.202, 307.572, 30.682],
[307.106, 306.876, 28.660],
[309.317, 312.490, 30.230],
[307.435, 310.151, 29.318],
[308.253, 306.300, 28.881],
[306.650, 309.301, 28.905],
[308.069, 306.831, 29.189],
[309.671, 308.834, 29.029],
[308.255, 309.955, 29.267],
[307.546, 308.613, 28.963],
[311.036, 309.206, 28.913],
[307.518, 308.175, 29.069],
[309.950, 311.262, 29.990],
[312.160, 310.772, 29.080],
[311.988, 312.709, 30.514]
]

In [4]:
xyz_1 = [i + [1.] for i in xyz]
xyz_1

[[312.747, 309.14, 30.086, 1.0],
 [305.796, 311.649, 30.356, 1.0],
 [307.694, 312.358, 30.418, 1.0],
 [310.149, 307.186, 29.298, 1.0],
 [311.937, 310.105, 29.216, 1.0],
 [311.202, 307.572, 30.682, 1.0],
 [307.106, 306.876, 28.66, 1.0],
 [309.317, 312.49, 30.23, 1.0],
 [307.435, 310.151, 29.318, 1.0],
 [308.253, 306.3, 28.881, 1.0],
 [306.65, 309.301, 28.905, 1.0],
 [308.069, 306.831, 29.189, 1.0],
 [309.671, 308.834, 29.029, 1.0],
 [308.255, 309.955, 29.267, 1.0],
 [307.546, 308.613, 28.963, 1.0],
 [311.036, 309.206, 28.913, 1.0],
 [307.518, 308.175, 29.069, 1.0],
 [309.95, 311.262, 29.99, 1.0],
 [312.16, 310.772, 29.08, 1.0],
 [311.988, 312.709, 30.514, 1.0]]

In [5]:
len(u_v)

20

In [6]:
A = []
for i in range(20):
    first_eq = xyz_1[i] + [0, 0, 0, 0] + [-u_v[i][0] * s for s in xyz_1[i]]
    second_eq = [0, 0, 0, 0] + xyz_1[i] + [-u_v[i][1] * s for s in xyz_1[i]]
    A.append(first_eq)
    A.append(second_eq)

A

[[312.747,
  309.14,
  30.086,
  1.0,
  0,
  0,
  0,
  0,
  -275217.36,
  -272043.2,
  -26475.68,
  -880.0],
 [0,
  0,
  0,
  0,
  312.747,
  309.14,
  30.086,
  1.0,
  -66927.85800000001,
  -66155.95999999999,
  -6438.4039999999995,
  -214.0],
 [305.796,
  311.649,
  30.356,
  1.0,
  0,
  0,
  0,
  0,
  -13149.228,
  -13400.907,
  -1305.308,
  -43.0],
 [0,
  0,
  0,
  0,
  305.796,
  311.649,
  30.356,
  1.0,
  -62076.587999999996,
  -63264.747,
  -6162.268,
  -203.0],
 [307.694,
  312.358,
  30.418,
  1.0,
  0,
  0,
  0,
  0,
  -83077.38,
  -84336.66,
  -8212.86,
  -270.0],
 [0,
  0,
  0,
  0,
  307.694,
  312.358,
  30.418,
  1.0,
  -60615.718,
  -61534.526,
  -5992.346,
  -197.0],
 [310.149,
  307.186,
  29.298,
  1.0,
  0,
  0,
  0,
  0,
  -274792.014,
  -272166.796,
  -25958.028,
  -886.0],
 [0,
  0,
  0,
  0,
  310.149,
  307.186,
  29.298,
  1.0,
  -107621.703,
  -106593.54199999999,
  -10166.405999999999,
  -347.0],
 [311.937,
  310.105,
  29.216,
  1.0,
  0,
  0,
  0,
  0,
  

In [7]:
A = np.array(A)
A.shape

(40, 12)

## SVD
### b) Given the following corresponding points, determine the camera projection matrix P using the SVD method. 

In [8]:
U, S, Vh = np.linalg.svd(A, full_matrices=True)

In [9]:
Vh.shape

(12, 12)

In [10]:
Vh[-1, :].reshape(3, 4)

array([[ 3.09963996e-03,  1.46204548e-04, -4.48497465e-04,
        -9.78930678e-01],
       [ 3.07018252e-04,  6.37193664e-04, -2.77356178e-03,
        -2.04144405e-01],
       [ 1.67933533e-06,  2.74767684e-06, -6.83964827e-07,
        -1.32882928e-03]])

## Result (raw)
[[ 3.09963996e-03,  1.46204548e-04, -4.48497465e-04,-9.78930678e-01],\
 [ 3.07018252e-04,  6.37193664e-04, -2.77356178e-03,-2.04144405e-01],\
 [ 1.67933533e-06,  2.74767684e-06, -6.83964827e-07,-1.32882928e-03]]

In [14]:
Vh[:, -1]

array([ 2.28079700e-03, -2.79974909e-04,  1.68725511e-03, -2.33393396e-03,
       -1.79002114e-03,  9.99215323e-01,  5.00807112e-03,  3.55413622e-02,
       -4.54385324e-03,  1.55320981e-02,  1.80393904e-04, -1.32882928e-03])

In [15]:
constant = 1 / Vh[-1, -1]

In [16]:
p = Vh[-1, :] * constant
p.reshape(3, 4)

array([[-2.33260962e+00, -1.10025080e-01,  3.37513233e-01,
         7.36686567e+02],
       [-2.31044166e-01, -4.79515070e-01,  2.08722206e+00,
         1.53627263e+02],
       [-1.26377057e-03, -2.06774255e-03,  5.14712341e-04,
         1.00000000e+00]])

## Result (setting $m_{34}= 1$)

[-2.33260962e+00, -1.10025080e-01,  3.37513233e-01,
         7.36686567e+02],\
       [-2.31044166e-01, -4.79515070e-01,  2.08722206e+00,
         1.53627263e+02],\
       [-1.26377057e-03, -2.06774255e-03,  5.14712341e-04,
         1.00000000e+00]]

# Pseudo-Inverse
## c)  Determine P for the data in b) using the pseudo inverse method. 

In [21]:
A_tild = A[:, :-1]
A_tild.shape

(40, 11)

In [43]:
b = np.array(u_v)
b = b.reshape(-1)
b

array([880, 214,  43, 203, 270, 197, 886, 347, 745, 302, 943, 128, 476,
       590, 419, 214, 317, 335, 783, 521, 235, 427, 665, 429, 655, 362,
       427, 333, 412, 415, 746, 351, 434, 415, 525, 234, 716, 308, 602,
       187])

In [31]:
A_dagger = np.linalg.pinv(A_tild)
p_tild = A_dagger @ b
p_tild

array([-2.33259098e+00, -1.09993113e-01,  3.37413916e-01,  7.36673920e+02,
       -2.31050254e-01, -4.79506029e-01,  2.08717636e+00,  1.53627756e+02,
       -1.26379606e-03, -2.06770917e-03,  5.14635233e-04])

In [36]:
p = np.append(p_tild, 1)
P = p.reshape(3, 4)
P

array([[-2.33259098e+00, -1.09993113e-01,  3.37413916e-01,
         7.36673920e+02],
       [-2.31050254e-01, -4.79506029e-01,  2.08717636e+00,
         1.53627756e+02],
       [-1.26379606e-03, -2.06770917e-03,  5.14635233e-04,
         1.00000000e+00]])